/* DO NOT EDIT!
   This file was automatically generated by m68k-palmos-multigen v2.2
   from sections.def  */

	.file	"sections.s"

	.globl	__text__
	.lcomm	__text__,4
	.globl	__text__perfsect
	.lcomm	__text__perfsect,4
	.globl	__text__miscsect
	.lcomm	__text__miscsect,4

.text
	.globl	_GccRelocateData
_GccRelocateData:
	bra.w	_GccLoadCodeAndRelocateData

.section ehook
	.long	_GccReleaseCode
